# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test+build type-injector

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: 16

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node Node.js ${{env.NODE_VERSION}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node Node.js ${{env.NODE_VERSION}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
    - run: npm ci
    - run: npm run coverage
    - name: archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html
        path: coverage/

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node Node.js ${{env.NODE_VERSION}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
    - run: npm ci
    - run: npm run bundle
    - run: npm pack
    - name: extract version
      run: echo "PACKAGE_FILENAME=$(ls -1 type-injector*.tgz)" >> $GITHUB_ENV
    - name: log extracted version
      run: echo PACKAGE_FILENAME $PACKAGE_FILENAME
    - name: archive build results
      uses: actions/upload-artifact@v3
      with:
        name: build-results
        path: dist/
    - name: archive npm package
      uses: actions/upload-artifact@v3
      with:
        path: type-injector*.tgz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
